import Image from "next/image";
import Head from "next/head";
import Hero from "@/src/components/Hero";
import AboutUs from "@/src/components/AboutUs";
import PodcastHome from "@/src/components/PodcastHome";
import OurFitur from "@/src/components/OurFitur";

export default function Home() {
  return (
    <>
      <Head>
        <title>HIMTIKA ー Himpunan Mahasiswa Informatika UNSIKA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/public/logo/HIMTIKA.png" />
      </Head>
      <Hero />
      <AboutUs />
      <PodcastHome />
      <OurFitur />
    </>
  )
}
